import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // tutorialSidebar: [
  //   'intro',
  //   {
  //     type: 'category',
  //     label: 'Getting Started',
  //     items: [
  //       'getting-started/installation',
  //       'getting-started/quickstart',
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: 'Core Concepts',
  //     items: [
  //       'core-concepts/transactions',
  //     ],
  //   },
  // ],
  
  // // API Reference sidebar
  // apiSidebar: [
  //   'api/overview',
  //   {
  //     type: 'category',
  //     label: 'API Reference',
  //     items: [
  //       'api/authentication',
  //     ],
  //   },
  // ],
};

export default sidebars;
